trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  repositoryName: 'pipelines-javascript-docker' 

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'techlabvn_dockerhub'
    repository: 'techlabvn/pipelines-javascript-docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile' # find source directory in clude sub directory for docker file