trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  repositoryName: 'techlabvn/pipelines-javascript-docker' # enter your Docker repository name you want to push image

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'techlabvn_dockerhub' #enter your connection
    repository: $(repositoryName) 
    command: 'buildAndPush'	# Build and push to repository
    Dockerfile: '**/Dockerfile'
