trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        repository: 'techlabvn/pipelines-javascript-docker'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        containerRegistry: 'techlabvn_dockerhub'
        repository: 'techlabvn/pipelines-javascript-docker'
        tags: |
          $(tag)
