trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(Build.Repository.Name):$(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'techlabvn_dockerhub'
        repository: 'techlabvn_dockerhub/$(Build.Repository.Name)'
        command: push
        tags: |
          $(tag)
