trigger:
- main

resources:
- repo: self
stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'techlabvn_dockerhub'
          repository: 'pipelines-javascript-docker'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'