trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  repositoryName: 'pipelines-javascript-docker' 

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'techlabvn_dockerhub'
    repository: $(repositoryName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'