trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  repositoryName: 'techlabvn_dockerhub' # enter your repository name

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'techlabvn_dockerhub' #enter your connection
    repository: $(repositoryName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
